modLoader = "javafml" #mandatory
loaderVersion = "[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
issueTrackerURL = "https://github.com/jingshenSN2/CraftTime/issues" #optional
[[mods]] #mandatory
modId = "crafttakestime" #mandatory
version = "1.0.1" #mandatory
displayName = "Craft Takes Time" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/craft-time" #optional
logoFile = "icon.png" #optional
credits = "" #optional
authors = "SN2" #optional
description = ''' Time to craft!
'''
[[dependencies.crafttakestime]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[35,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.crafttakestime]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"